### ISSUE TITLE
Missing alignment in table cells

### ISSUE THREAD

**Issue by xrat** [schulle4u/yellow-wittstock#1]
Yellow's Markdown table syntax supports alignment via `:` as in

``` markdown
| Item      | Value |
| --------- | -----:|
| Computer  | $1600 |
| Phone     |   $12 |
```

Yellow renders the line with "Phone" as

``` html
<tr>
  <td>Phone</td>
  <td align="right">$12</td>
</tr>
```

but yellow-wittstock has no CSS to right-align the `<td`.

One way to achieve it would be

``` css
td[align="right"] { text-align: right; }
td[align="center"] { text-align: center; }
```

P.S.: Fantastic theme. Thanks so much for it.
