### ISSUE TITLE
Missing alignment for images

### ISSUE THREAD

**Issue by xrat** [schulle4u/yellow-wittstock#2]
2 of the often featured ways to include images in Yellow are `![](location)` and `[image …]` as provided by [annaesvensson/yellow-image](https://github.com/annaesvensson/yellow-image). For both, image alignment is supported, as e.g. in

``` markdown
![](smallphoto.jpg){.right}

[image smallphoto.jpg "title" right]
```

The generated HTML is in both cases (slightly simplified):

``` html
<img src="smallphoto.jpg" … class="right">
```

But yellow-wittstock has no CSS for `.right`. If you want to support image alignment, one way would be

``` css
img.right { float: right; margin-left: 1rem; }
img.left { float: left; margin-right: 1rem; }
img.center { margin: 0 auto; }
```

Other Yellow themes typically have something like

``` css
.content .right {
    float: right;
    margin: 0 0 0 1em;
}
```
